### PR TITLE
Fix STV recording not stopping after match end

### LINKED ISSUE #42: SourceTV doesn't toggle correctly
SourceTV doesn't end recording after a competitive match is finished.

### PR DESCRIPTION
**Pull request by Rainyan**
Fix #42

### CODE REVIEW

**Comment by Rainyan** [comment]
@bauxiteDYS I can't reproduce this bug. Here's what I've tried, using [v0.6.0](https://github.com/Rainyan/sourcemod-nt-competitive/releases/tag/v0.6.0) (the tag just before this change):

```
sv_cheats 1; bot_add; bot_add; sv_cheats 0 // need player in both teams
sm_forcelive // force start match
// (wait for the match start countdown...)
sm_forcelive;sm_forcelive // force end match
```

But I'm seeing the SourceTV replays in `NeotokyoSource/replays_competitive` being started and stopped correctly.

**Comment by bauxiteDYS** [comment]
Yeah, now when you end the match, note the size of the demo, then do some actions for a few minutes and refresh the folder, the demo file size should increase, it will keep slowly increasing until the map changes. If that doesn't work then I'll have to check again.

**Comment by Rainyan** [comment]
Doesn't seem to be the case for me. Here's the printout from the local SRCDS:

    ] sm_forcelive
    Recording SourceTV demo to replays_competitive/20231121-0405_nt_dawn_Ctg_1700532300.dem...
    ] sm_forcelive
    [COMP] Stopping a competitive match, are you sure?
    Please repeat the command to confirm.
    ] sm_forcelive
    Completed SourceTV demo "replays_competitive/20231121-0405_nt_dawn_Ctg_1700532300.dem", recording time 10.7

Inspecting the OS file handles, no app is accessing the demo file after this.

Are you sure this is not in fact a duplicate of ec652a6cf3631bc606ea4cd0cd14bf93c9a1cc18? Glancing at the code change here, it doesn't seem obvious why moving the `ToggleSourceTV` call up in the function body would affect this behaviour.

Same deal if I create a match between 2 bots with `sm_competitive_round_limit 1`, forcelive and then slay one of the bots to force a match conclusion manually.

**Comment by Rainyan** [comment]
Ok, there's something weird going on here. After ending the match with a slay, `sm_forcelive` still considers the match as active:

    ] sm_slay #6
    L 11/21/2023 - 04:21:23: [playercommands.smx] "Console<0><Console><Console>" slayed "<6><BOT><>"
    L 11/21/2023 - 04:21:23: "<6><BOT><Jinrai>" committed suicide with "player"
    Death HitLocation 2
    [SM] Slayed .
    Completed SourceTV demo "replays_competitive/20231121-0421_nt_dawn_ctg_0.dem", recording time 34.7
    ] sm_forcelive
    [COMP] Stopping a competitive match, are you sure?
    Please repeat the command to confirm.

Not sure if this is related to this bug.

**Comment by Rainyan** [comment]
Ok, so bisecting the git history, I can reproduce the replay not stopping bug starting from commit d406a5aa5100d176d277ec2e0e61b2f858c5bdea. Which is strange because that commit is from yesterday, well after this bugfix was made. For v0.6.0 and v0.7.0, it doesn't seem to happen. I'll have to investigate some more as currently I've no clue what's triggering the problem.

**Comment by Rainyan** [comment]
While this change does toggle the recording, it also breaks the replay filename, since it relies on the timestamp creation code that happens before the call to `ToggleSourceTV`, so you end up with demos where the epoch timestamp following the map name is zero:

    Recording SourceTV demo to replays_competitive/20231121-0524_nt_dawn_ctg_0.dem...

edit: removed incorrect stuff

**Comment by bauxiteDYS** [comment]
Hmm interesting, although I'm almost 99% sure that versions including and before 0.6.0 the stv doesn't stop recording, perhaps it's only on NSF win? I'll have to test that, but I don't believe so.

**Comment by Rainyan** [comment]
It seems [c9fbd6d](https://github.com/Rainyan/sourcemod-nt-competitive/pull/44/commits/c9fbd6da42fe21754b498cd249a2ced4aeacd6f5) fixed the underlying bug here.

**Comment by bauxiteDYS** [comment]
Yeah that makes sense

**Comment by Rainyan** [comment]
Ok, I think it all works now. Thanks again for the PR!

**Pull request merged**
